
services:
  app:
    build: .
    image: ppo
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: nastya
      DB_PASSWORD: nastya
      DB_NAME: mydb
      DATABASE_URL: "postgresql://nastya:nastya@db:5432/mydb"
      MONGO_URI: "mongodb://admin:password@mongodb:27017"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      mongodb: 
        condition: service_healthy
    networks:
      - my_network
  test-db:
    image: postgres:15
    container_name: postgres_test
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d/
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - my_network
  
  unit-tests:
    build: .
    container_name: unit_tests_runner
    environment:
      DATABASE_URL: "postgresql+asyncpg://test_user:test_password@test-db:5432/test_db"
      TEST_ENV: "unit"
    volumes:
      - ./allure-results:/app/allure-results
      - ./test-reports:/app/test-reports
    depends_on:
      test-db:
        condition: service_healthy
    networks:
      - my_network
    command: >
      sh -c "
        pytest tests/unit/ -v --alluredir=/app/allure-results/unit"
    profiles: ["test"]

  integration-tests:
    build: .
    container_name: integration_tests_runner
    environment:
      DATABASE_URL: "postgresql+asyncpg://test_user:test_password@test-db:5432/test_db"
      TEST_ENV: "integration"
    volumes:
      - ./allure-results:/app/allure-results
      - ./test-reports:/app/test-reports
    depends_on:
      test-db:
        condition: service_healthy
      unit-tests:
        condition: service_completed_successfully
    networks:
      - my_network
    command: >
      sh -c "
        pytest tests/integration/ -v --alluredir=/app/allure-results/integration"
    profiles: ["test"]

  allure:
    image: frankescobar/allure-docker-service
    ports:
      - "5050:5050"
    volumes:
      - ./allure-results:/app/allure-results
    networks:
      - my_network

  db:
    image: postgres:15
    container_name: postgres_container_test_debug
    environment:
      POSTGRES_USER: nastya
      POSTGRES_PASSWORD: nastya
      POSTGRES_DB: mydb
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d/
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nastya -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - my_network

  mongodb:
    image: mongo:latest
    container_name: mongodb_web
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping').ok", "-u", "admin", "-p", "password", "--quiet"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - my_network
    restart: unless-stopped 

volumes:
  postgres_data:
  postgres_test_data:
  mongodb_data:
  allure-results:

networks:
  my_network:
    driver: bridge